export enum MutaionType {
  ROUTER_SET_ROUTES = 'SET_ROUTES',
  USER_SET_TOKEN = 'SET_TOKEN',
  USER_SET_ROLES = 'SET_ROLES',
  APP_SET_MODE = 'APP_SET_MODE',
  APP_SET_IS_COLLAPSE = 'APP_SET_IS_COLLAPSE'
}
